### PR TITLE
Github actions demo

### PR DESCRIPTION
**Pull request by pratikk-databricks**
Added github actions demo similar to the Azure devops pipeline.
Updated the readme file.

### CODE REVIEW

**Review by alexott — CHANGES_REQUESTED** [review]
Azure versions uses two directories - one is for testing of the data (staging), and another - for  deployment itself (production). Otherwise each test run will affect the production deployment.

Just add another parameter, and use corresponding names - `staging_repo_directory` and `production_repo_directory`.

**Comment by alexott** [comment]
Also, exclude the `.github` changes in the `azure-pipelines.yaml` so changes in it won't trigger the build.

**Comment by pratikk-databricks** [comment]
.github is already excluded in the azure-pipelines.yml
In the github setup, I have used the environments. Where each environment will have a value for $REPO_DIRECTORY corresponding to the its workspace. For example production env will have url for production workspace and similar for staging and dev.
I have mentioned this in the README as well.
Should I change this to having different variable names instead of having environement?

**Review by alexott — APPROVED** [review]
thank you

**Pull request merged**
